name: flutter_material_pickers_example
description: A Flutter project that demonstrated the use of the flutter_material_pickers package.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_material_pickers:
    path: ../
  dynamic_theme: ^1.0.0
  intl: ^0.17.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
